import { FieldRequirement } from '@prisma/client';

export type TransportBookingFieldRule = {
  key: string;
  label: string;
  xmlPath: string;
  requirement: FieldRequirement;
  calculable?: boolean;
  generated?: boolean;
  conditional?: boolean;
  aliases?: string[];
};

const REQUIRED = FieldRequirement.REQUIRED;
const RECOMMENDED = FieldRequirement.RECOMMENDED;
const OPTIONAL = FieldRequirement.OPTIONAL;

export const TRANSPORT_BOOKING_FIELD_RULES: TransportBookingFieldRule[] = [
  // Technical / system
  {
    key: 'edireference',
    label: 'EDI reference',
    xmlPath: 'transportbooking.edireference',
    requirement: OPTIONAL,
    generated: true,
    aliases: ['edireference', 'edi reference', 'edi-ref'],
  },
  {
    key: 'reference',
    label: 'Reference',
    xmlPath: 'transportbooking.reference',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['reference', 'ref'],
  },
  {
    key: 'customer_id',
    label: 'Customer ID',
    xmlPath: 'transportbooking.customer_id',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['customer id', 'customer_id', 'klantnummer', 'client id'],
  },
  {
    key: 'shipment_edireference',
    label: 'Shipment EDI reference',
    xmlPath: 'transportbooking.shipments.shipment.edireference',
    requirement: OPTIONAL,
    generated: true,
    aliases: ['shipment edireference', 'shipment edi reference'],
  },
  {
    key: 'shipment_reference',
    label: 'Shipment reference',
    xmlPath: 'transportbooking.shipments.shipment.reference',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['shipment reference', 'shipment ref'],
  },

  // Pickup
  {
    key: 'pickup_reference',
    label: 'Pickup reference',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.reference',
    requirement: RECOMMENDED,
    aliases: [
      'pickup reference',
      'loading reference',
      'collection reference',
      'ophaalreferentie',
      'laadreferentie',
    ],
  },
  {
    key: 'pickup_date',
    label: 'Pickup date',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.date',
    requirement: REQUIRED,
    aliases: [
      'pickup date',
      'pickup date from',
      'loading date',
      'collection date',
      'laaddatum',
    ],
  },
  {
    key: 'pickup_date_till',
    label: 'Pickup date till',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.datetill',
    requirement: RECOMMENDED,
    aliases: [
      'pickup date till',
      'pickup date to',
      'pickup until date',
      'loading date till',
      'loading date to',
      'collection date till',
      'laaddatum tot',
    ],
  },
  {
    key: 'pickup_time',
    label: 'Pickup time',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.time',
    requirement: RECOMMENDED,
    aliases: [
      'pickup time',
      'pickup time from',
      'loading time',
      'collection time',
      'laadtijd',
    ],
  },
  {
    key: 'pickup_time_till',
    label: 'Pickup time till',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.timetill',
    requirement: RECOMMENDED,
    aliases: [
      'pickup time till',
      'pickup time to',
      'pickup until',
      'loading until',
      'laadtijd tot',
      'till',
    ],
  },
  {
    key: 'pickup_time_delivery',
    label: 'Pickup time delivery',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.time_delivery',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['pickup time delivery', 'loading delivery time'],
  },
  {
    key: 'pickup_name',
    label: 'Pickup name',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.name',
    requirement: RECOMMENDED,
    aliases: ['pickup name', 'loading name', 'collection name', 'laadnaam'],
  },
  {
    key: 'pickup_address',
    label: 'Pickup address',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.address1',
    requirement: REQUIRED,
    aliases: [
      'pickup address',
      'pickup address1',
      'loading address',
      'collection address',
      'pickup street',
      'laadadres',
      'adres laden',
    ],
  },
  {
    key: 'pickup_address2',
    label: 'Pickup address 2',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.address2',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['pickup address2', 'pickup address 2', 'loading address 2'],
  },
  {
    key: 'pickup_country',
    label: 'Pickup country',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.country_id',
    requirement: REQUIRED,
    aliases: ['pickup country', 'loading country', 'land laden', 'laadland'],
  },
  {
    key: 'pickup_zipcode',
    label: 'Pickup zipcode',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.zipcode',
    requirement: REQUIRED,
    aliases: [
      'pickup zipcode',
      'pickup postcode',
      'loading zipcode',
      'postcode laden',
      'laadpostcode',
    ],
  },
  {
    key: 'pickup_city',
    label: 'Pickup city',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.city_id',
    requirement: REQUIRED,
    aliases: [
      'pickup city',
      'loading city',
      'plaats laden',
      'stad laden',
      'laadplaats',
    ],
  },
  {
    key: 'pickup_remarks',
    label: 'Pickup remarks',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.remarks',
    requirement: OPTIONAL,
    aliases: ['pickup remarks', 'loading remarks', 'pickup notes'],
  },
  {
    key: 'pickup_contact',
    label: 'Pickup contact',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.contact',
    requirement: RECOMMENDED,
    aliases: ['pickup contact', 'loading contact', 'laad contact'],
  },
  {
    key: 'pickup_phone',
    label: 'Pickup phone',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.phone',
    requirement: RECOMMENDED,
    aliases: ['pickup phone', 'loading phone', 'laad telefoonnummer'],
  },
  {
    key: 'pickup_email',
    label: 'Pickup email',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.email',
    requirement: OPTIONAL,
    aliases: ['pickup email', 'loading email', 'laad e-mailadres'],
  },
  {
    key: 'neutral_pickup_address',
    label: 'Neutral pickup address',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.neutral_loading',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['neutral pickup address', 'neutral loading'],
  },
  {
    key: 'driver_pickup_info',
    label: 'Driver pickup info',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.driver_info',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['driver pickup info', 'pickup driver info'],
  },

  // Delivery
  {
    key: 'delivery_reference',
    label: 'Delivery reference',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.reference',
    requirement: RECOMMENDED,
    aliases: [
      'delivery reference',
      'unloading reference',
      'afleverreferentie',
      'losreferentie',
    ],
  },
  {
    key: 'delivery_date',
    label: 'Delivery date',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.date',
    requirement: REQUIRED,
    aliases: [
      'delivery date',
      'delivery date from',
      'unloading date',
      'afleverdatum',
      'losdatum',
    ],
  },
  {
    key: 'delivery_time',
    label: 'Delivery time',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.time',
    requirement: RECOMMENDED,
    aliases: [
      'delivery time',
      'delivery time from',
      'unloading time',
      'aflevertijd',
      'lostijd',
    ],
  },
  {
    key: 'delivery_time_till',
    label: 'Delivery time till',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.timetill',
    requirement: RECOMMENDED,
    aliases: [
      'delivery time till',
      'delivery time to',
      'delivery until',
      'unloading until',
      'aflevertijd tot',
    ],
  },
  {
    key: 'delivery_time_delivery',
    label: 'Delivery time delivery',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.time_delivery',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['delivery time delivery', 'unloading delivery time'],
  },
  {
    key: 'delivery_name',
    label: 'Delivery name',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.name',
    requirement: RECOMMENDED,
    aliases: ['delivery name', 'unloading name', 'losnaam'],
  },
  {
    key: 'delivery_address',
    label: 'Delivery address',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.address1',
    requirement: REQUIRED,
    aliases: [
      'delivery address',
      'delivery address1',
      'unloading address',
      'delivery street',
      'afleveradres',
      'adres lossen',
      'losadres',
    ],
  },
  {
    key: 'delivery_address2',
    label: 'Delivery address 2',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.address2',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['delivery address2', 'delivery address 2', 'unloading address 2'],
  },
  {
    key: 'delivery_country',
    label: 'Delivery country',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.country_id',
    requirement: REQUIRED,
    aliases: ['delivery country', 'unloading country', 'land lossen', 'losland'],
  },
  {
    key: 'delivery_zipcode',
    label: 'Delivery zipcode',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.zipcode',
    requirement: REQUIRED,
    aliases: [
      'delivery zipcode',
      'delivery postcode',
      'postcode lossen',
      'postcode aflever',
      'lospostcode',
    ],
  },
  {
    key: 'delivery_city',
    label: 'Delivery city',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.city_id',
    requirement: REQUIRED,
    aliases: [
      'delivery city',
      'unloading city',
      'plaats lossen',
      'stad lossen',
      'losplaats',
    ],
  },
  {
    key: 'delivery_remarks',
    label: 'Delivery remarks',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.remarks',
    requirement: OPTIONAL,
    aliases: ['delivery remarks', 'unloading remarks', 'delivery notes'],
  },
  {
    key: 'delivery_contact',
    label: 'Delivery contact',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.contact',
    requirement: RECOMMENDED,
    aliases: ['delivery contact', 'unloading contact', 'los contact'],
  },
  {
    key: 'delivery_phone',
    label: 'Delivery phone',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.phone',
    requirement: RECOMMENDED,
    aliases: ['delivery phone', 'unloading phone', 'los telefoonnummer'],
  },
  {
    key: 'delivery_email',
    label: 'Delivery email',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.email',
    requirement: OPTIONAL,
    aliases: ['delivery email', 'unloading email', 'los e-mailadres'],
  },
  {
    key: 'neutral_delivery_address',
    label: 'Neutral delivery address',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.neutral_unloading',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['neutral delivery address', 'neutral unloading'],
  },
  {
    key: 'driver_delivery_info',
    label: 'Driver delivery info',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.driver_info',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['driver delivery info', 'delivery driver info'],
  },

  // General / cargo
  {
    key: 'unit_amount',
    label: 'Unit amount',
    xmlPath: 'transportbooking.shipments.shipment.cargo.unitamount',
    requirement: OPTIONAL,
    aliases: ['unit amount', 'units', 'aantal', 'quantity', 'qty'],
  },
  {
    key: 'unit_id',
    label: 'Unit id',
    xmlPath: 'transportbooking.shipments.shipment.cargo.unit_id',
    requirement: OPTIONAL,
    aliases: ['unit id', 'unit', 'eenheid', 'colli', 'packaging', 'pallet', 'pcs'],
  },
  {
    key: 'weight',
    label: 'Weight',
    xmlPath: 'transportbooking.shipments.shipment.cargo.weight',
    requirement: OPTIONAL,
    aliases: ['weight', 'gewicht', 'kg', 'total weight'],
  },
  {
    key: 'cargo_unit_amount',
    label: 'Cargo unit amount',
    xmlPath: 'transportbooking.shipments.shipment.cargo.unitamount',
    requirement: REQUIRED,
    aliases: ['cargo unit amount', 'unit amount', 'units', 'aantal', 'quantity', 'qty'],
  },
  {
    key: 'cargo_unit_id',
    label: 'Cargo unit id',
    xmlPath: 'transportbooking.shipments.shipment.cargo.unit_id',
    requirement: REQUIRED,
    aliases: ['cargo unit id', 'unit id', 'unit', 'colli', 'packaging', 'pallet', 'pcs'],
  },
  {
    key: 'cargo_weight',
    label: 'Cargo weight',
    xmlPath: 'transportbooking.shipments.shipment.cargo.weight',
    requirement: RECOMMENDED,
    aliases: ['cargo weight', 'weight', 'gewicht', 'kg', 'total weight'],
  },
  {
    key: 'invoice_reference',
    label: 'Invoice reference',
    xmlPath: 'transportbooking.reference',
    requirement: REQUIRED,
    aliases: ['invoice reference', 'factuurreferentie', 'factuur referentie'],
  },
  {
    key: 'product_id',
    label: 'Product',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.product_id',
    requirement: RECOMMENDED,
    aliases: ['product', 'product id', 'goods', 'omschrijving', 'cargo'],
  },
  {
    key: 'product_description',
    label: 'Product description',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.description',
    requirement: RECOMMENDED,
    conditional: true,
    aliases: ['product description', 'goods description'],
  },
  {
    key: 'cargo_loading_meter',
    label: 'Cargo loading meter',
    xmlPath: 'transportbooking.shipments.shipment.cargo.loadingmeter',
    requirement: RECOMMENDED,
    calculable: true,
    aliases: ['loadingmeter', 'loading meter', 'laadmeter', 'ldm'],
  },
  {
    key: 'cargo_volume',
    label: 'Cargo volume',
    xmlPath: 'transportbooking.shipments.shipment.cargo.volume',
    requirement: RECOMMENDED,
    calculable: true,
    aliases: ['volume', 'm3', 'cbm', 'kubieke meter'],
  },
  {
    key: 'pallet_places',
    label: 'Pallet places',
    xmlPath: 'transportbooking.shipments.shipment.cargo.pallet_places',
    requirement: RECOMMENDED,
    conditional: true,
    aliases: ['pallet places', 'pallets', 'pallet places count'],
  },
  {
    key: 'length',
    label: 'Length',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.length',
    requirement: RECOMMENDED,
    aliases: ['length', 'lengte', 'comprimento', 'cm', 'm'],
  },
  {
    key: 'width',
    label: 'Width',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.width',
    requirement: RECOMMENDED,
    aliases: ['width', 'breedte', 'largura'],
  },
  {
    key: 'height',
    label: 'Height',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.height',
    requirement: RECOMMENDED,
    aliases: ['height', 'hoogte', 'altura'],
  },
  {
    key: 'transport_type',
    label: 'Transport type',
    xmlPath: 'transportbooking.shipments.shipment.transport_type',
    requirement: RECOMMENDED,
    aliases: ['transport type', 'transportsoort'],
  },
  {
    key: 'adr_class',
    label: 'ADR class',
    xmlPath: 'transportbooking.shipments.shipment.cargo.adr_class',
    requirement: RECOMMENDED,
    conditional: true,
    aliases: ['adr class', 'adr klasse'],
  },
  {
    key: 'dangerous_goods',
    label: 'Dangerous goods',
    xmlPath: 'transportbooking.shipments.shipment.cargo.dangerous_goods',
    requirement: RECOMMENDED,
    conditional: true,
    aliases: ['dangerous goods', 'hazmat', 'gevaarlijke goederen'],
  },
  {
    key: 'fixed_price',
    label: 'Fixed price',
    xmlPath: 'transportbooking.shipments.shipment.cargo.price',
    requirement: RECOMMENDED,
    conditional: true,
    aliases: ['fixed price', 'price', 'prijs', 'valor', 'eur'],
  },

  // Calculated / derived non-blocking
  {
    key: 'external_shipment_id',
    label: 'External shipment id',
    xmlPath: 'transportbooking.shipments.shipment.cargo.externalshipmentid',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['external shipment id', 'externalshipmentid', 'invoice reference'],
  },
  {
    key: 'barcode',
    label: 'Barcode',
    xmlPath: 'transportbooking.shipments.shipment.cargo.barcode',
    requirement: OPTIONAL,
    generated: true,
    aliases: ['barcode', 'bar code'],
  },
  {
    key: 'cmr_number',
    label: 'CMR number',
    xmlPath: 'transportbooking.shipments.shipment.cargo.cmrnumber',
    requirement: OPTIONAL,
    aliases: ['cmr', 'cmr number', 'cmrnumber'],
  },
  {
    key: 'goods_unit_amount',
    label: 'Goods unit amount',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.unitamount',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['goods unit amount'],
  },
  {
    key: 'goods_unit_id',
    label: 'Goods unit id',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.unit_id',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['goods unit id'],
  },
  {
    key: 'goods_weight',
    label: 'Goods weight',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.weight',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['goods weight'],
  },
  {
    key: 'goods_loading_meter',
    label: 'Goods loading meter',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.loadingmeter',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['goods loading meter'],
  },
  {
    key: 'goods_volume',
    label: 'Goods volume',
    xmlPath: 'transportbooking.shipments.shipment.cargo.goodslines.goodsline.volume',
    requirement: OPTIONAL,
    calculable: true,
    aliases: ['goods volume'],
  },

  // Legacy / extra optional fields we still keep when present
  {
    key: 'product_instructions',
    label: 'Product instructions',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.remarks',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['instructions', 'instructies', 'instrucoes', 'remarks', 'notes'],
  },
  {
    key: 'adr',
    label: 'ADR',
    xmlPath: 'transportbooking.shipments.shipment.cargo.adr',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['adr'],
  },
  {
    key: 'neutral_loading',
    label: 'Neutral loading',
    xmlPath: 'transportbooking.shipments.shipment.pickupaddress.neutral_loading',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['neutral loading', 'neutraal laden', 'carregamento neutro'],
  },
  {
    key: 'neutral_unloading',
    label: 'Neutral unloading',
    xmlPath: 'transportbooking.shipments.shipment.deliveryaddress.neutral_unloading',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['neutral unloading', 'neutraal lossen', 'descarga neutra'],
  },
  {
    key: 'sender',
    label: 'Sender',
    xmlPath: 'transportbooking.shipments.shipment.sender',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['sender', 'afzender', 'remetente'],
  },
  {
    key: 'crane_height',
    label: 'Crane height',
    xmlPath: 'transportbooking.shipments.shipment.cargo.crane_height',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['crane height', 'kraan hoogte', 'altura guindaste'],
  },
  {
    key: 'permits',
    label: 'Permits',
    xmlPath: 'transportbooking.shipments.shipment.cargo.permits',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['permit', 'permits', 'license', 'licence', 'vergunning'],
  },
  {
    key: 'escort_required',
    label: 'Escort required',
    xmlPath: 'transportbooking.shipments.shipment.cargo.escort_required',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['escort required', 'escort', 'begeleiding'],
  },
  {
    key: 'price',
    label: 'Price',
    xmlPath: 'transportbooking.shipments.shipment.cargo.price',
    requirement: OPTIONAL,
    conditional: true,
    aliases: ['price', 'prijs', 'valor', 'eur'],
  },
];

export function getRuleRequirement(rule: TransportBookingFieldRule) {
  return rule.requirement;
}

export function isRequiredFieldRule(rule: TransportBookingFieldRule) {
  return getRuleRequirement(rule) === FieldRequirement.REQUIRED;
}

export function isRecommendedFieldRule(rule: TransportBookingFieldRule) {
  return getRuleRequirement(rule) === FieldRequirement.RECOMMENDED;
}

export function isOptionalFieldRule(rule: TransportBookingFieldRule) {
  return getRuleRequirement(rule) === FieldRequirement.OPTIONAL;
}
